---
api_version: core/v2
type: Check
metadata:
  namespace: default
  name: alive_postgres
  labels: {}
  annotations:
    sensu.io.json_attributes: '{"occurrences":5,"opsgenie":{"tags":[":::opsgenie.tags:::"]}}'
    fatigue_check/occurrences: '5'
spec:
  command: postgres-alive.sh -U postgres -w postgres
  subscriptions:
  - Postgres
  publish: true
  interval: 60
  max_output_size: 1024
  handlers:
  - opsgenie
  runtime_assets:
  - postgres_sensu_checks
---
api_version: core/v2
type: Check
metadata:
  namespace: default
  name: connections_postgres
  labels: {}
  annotations:
    sensu.io.json_attributes: '{"occurrences":5,"opsgenie":{"tags":[":::opsgenie.tags:::"]}}'
    fatigue_check/occurrences: '5'
spec:
  command: postgres-connections.sh -W 1 -C 2 -U postgres -w postgres
  subscriptions:
  - Postgres
  publish: true
  interval: 60
  max_output_size: 1024
  handlers:
  - opsgenie
  runtime_assets:
  - postgres_sensu_checks